execute @a[m=!c] ~ ~ ~ detect ~ ~ ~ air 0 execute @s ~ ~ ~ detect ~ ~-1 ~ grass 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ grass 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ grass 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 grass 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 grass 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 grass 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 grass 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 grass 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 grass 0 execute @s ~ ~ ~ detect ~1 ~ ~ air 0 execute @s ~ ~ ~ detect ~-1 ~ ~ air 0 execute @s ~ ~ ~ detect ~ ~ ~1 air 0 execute @s ~ ~ ~ detect ~ ~ ~-1 air 0 execute @s ~ ~ ~ detect ~1 ~ ~1 air 0 execute @s ~ ~ ~ detect ~1 ~ ~-1 air 0 execute @s ~ ~ ~ detect ~-1 ~ ~1 air 0 execute @s ~ ~ ~ detect ~-1 ~ ~-1 air 0 execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock 0 execute @s ~ ~ ~ detect ~1 ~-4 ~ bedrock 0 execute @s ~ ~ ~ detect ~-1 ~-4 ~ bedrock 0 execute @s ~ ~ ~1 detect ~ ~-4 ~ bedrock 0 execute @s ~ ~ ~ detect ~ ~-4 ~-1 bedrock 0 execute @s ~ ~ ~ detect ~1 ~-4 ~1 bedrock 0 execute @s ~ ~ ~ detect ~1 ~-4 ~-1 bedrock 0 execute @s ~ ~ ~ detect ~-1 ~-4 ~1 bedrock 0 execute @s ~ ~ ~ detect ~-1 ~-4 ~-1 bedrock 0 tag @s add flat_error


execute @a[m=!c] ~ ~ ~ detect ~ ~ ~ air 0 execute @s ~ ~ ~ detect ~ ~-1 ~ grass 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ grass 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ grass 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 grass 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 grass 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 grass 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 grass 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 grass 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 grass 0 execute @s ~ ~ ~ detect ~1 ~ ~ air 0 execute @s ~ ~ ~ detect ~-1 ~ ~ air 0 execute @s ~ ~ ~ detect ~ ~ ~1 air 0 execute @s ~ ~ ~ detect ~ ~ ~-1 air 0 execute @s ~ ~ ~ detect ~1 ~ ~1 air 0 execute @s ~ ~ ~ detect ~1 ~ ~-1 air 0 execute @s ~ ~ ~ detect ~-1 ~ ~1 air 0 execute @s ~ ~ ~ detect ~-1 ~ ~-1 air 0 execute @s ~ ~ ~ detect ~ ~-4 ~ glass 0 execute @s ~ ~ ~ detect ~1 ~-4 ~ glass 0 execute @s ~ ~ ~ detect ~-1 ~-4 ~ glass 0 execute @s ~ ~ ~1 detect ~ ~-4 ~ glass 0 execute @s ~ ~ ~ detect ~ ~-4 ~-1 glass 0 execute @s ~ ~ ~ detect ~1 ~-4 ~1 glass 0 execute @s ~ ~ ~ detect ~1 ~-4 ~-1 glass 0 execute @s ~ ~ ~ detect ~-1 ~-4 ~1 glass 0 execute @s ~ ~ ~ detect ~-1 ~-4 ~-1 glass 0 tag @s add flat_error


execute @a[tag=flat_error] ~ ~ ~ say §a場外に出た可能性があります。

execute @a[tag=flat_error] ~ ~ ~ tp @s 0 17 0

execute @a[tag=flat_error] ~ ~ ~ tag @s remove flat_error